### ISSUE TITLE
Create CONTRIBUTORS.yaml

### ISSUE THREAD

**Issue by dgarijo** [EVERSE-ResearchSoftware/RSQKit#32] opened 2024-07-22 13:18 UTC
That's the file to render properly the contributors info in a yaml file.

**Comment by dgarijo** [comment] 2024-10-15 15:47
Done in https://github.com/EVERSE-ResearchSoftware/RSQKit/pull/75, but need to add all contributors!

**Comment by anenadic** [comment] 2024-12-06 12:49
Duplicate of #132.

**Closed by anenadic** 2024-12-06 12:49 UTC
